### ISSUE TITLE
After porting to pyproject.toml, rst.linker fails with error in Sphinx

### ISSUE THREAD

**Issue by jaraco** [jaraco/rst.linker#13]
In https://github.com/jaraco/tempora/actions/runs/8714844379/job/23905742259, the docs build is failing and it implicates rst.linker. Passing -v to the sphinx build provides more context:

```
docs: commands[0] /Users/jaraco/code/jaraco/tempora/docs> python -m sphinx -W --keep-going . /Users/jaraco/code/jaraco/tempora/build/html -v
Running Sphinx v7.3.3
loading pickled environment... done

Traceback (most recent call last):
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/rst/linker.py", line 211, in make_links
    replacer = Replacer.from_definition(defn, config_dict(app.config))
                                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/rst/linker.py", line 203, in config_dict
    return dict((key, getattr(config, key)) for key in config.values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/rst/linker.py", line 203, in <genexpr>
    return dict((key, getattr(config, key)) for key in config.values)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/config.py", line 412, in __getattr__
    return default(self)
           ^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/builders/latex/__init__.py", line 517, in default_latex_documents
    author = texescape.escape(config.author, config.latex_engine)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/util/texescape.py", line 110, in escape
    return s.translate(_tex_escape_map)
           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'translate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/application.py", line 339, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/jaraco/code/jaraco/tempora/.tox/docs/lib/python3.12/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function make_links at 0x104fa7ba0> for event 'builder-inited' threw an exception (exception: 'NoneType' object has no attribute 'translate')

Extension error (rst.linker):
Handler <function make_links at 0x104fa7ba0> for event 'builder-inited' threw an exception (exception: 'NoneType' object has no attribute 'translate')
docs: exit 2 (1.84 seconds) /Users/jaraco/code/jaraco/tempora/docs> python -m sphinx -W --keep-going . /Users/jaraco/code/jaraco/tempora/build/html -v pid=77376
  docs: FAIL code 2 (2.84=setup[1.01]+cmd[1.84] seconds)
  evaluation failed :( (2.88 seconds)
```

**Comment by jaraco** [comment]
Creating an empty `setup.cfg` doesn't help.

**Comment by jaraco** [comment]
Creating a `setup.cfg` with this content fixes the issue:

```
[metadata]
name = tempora
author = Jason R. Coombs
url = https://github.com/jaraco/tempora
```

Removing one of those keys but leaving others produces different obscure errors, suggesting the issue might actually be in [jaraco.packaging](/jaraco/jaraco.packaging).

**Comment by jaraco** [comment]
Indeed, removing jaraco.packaging and the things that rely on it also bypasses the issue, so the issue must be there.
