### ISSUE TITLE
FTBS: v1.10 -- missing egg info from setup.cfg

### ISSUE THREAD

**Issue by Corin-EU** [jaraco/rst.linker#6]
python3 --version
Python 3.5.2

If rst.linker v1.10 source code is downloaded from this repository, it fails to build using the setup.py file

     PYTHONPATH="/usr/lib/python3/dist-packages:/usr/local/lib/python3.5/dist-packages" \
     /usr/bin/python3.5 "/usr/src/build/rst.linker-1.10/setup.py" build

     Traceback (most recent call last):
       File "/usr/src/build/rst.linker-1.10/setup.py", line 74, in <module>
         setuptools.setup(**params)
       File "/usr/local/lib/python3.5/site-packages/setuptools-40.6.3.post20190119-py3.5.egg/setuptools/__init__.py", line 143, in setup
       File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
         _setup_distribution = dist = klass(attrs)
       File "/usr/local/lib/python3.5/site-packages/setuptools-40.6.3.post20190119-py3.5.egg/setuptools/dist.py", line 442, in __init__
       File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
         self.finalize_options()
       File "/usr/local/lib/python3.5/site-packages/setuptools-40.6.3.post20190119-py3.5.egg/setuptools/dist.py", line 601, in finalize_options
       File "/usr/src/build/rst.linker-1.10/.eggs/setuptools_scm-3.2.0-py3.5.egg/setuptools_scm/integration.py", line 23, in version_keyword
         dist.metadata.version = get_version(**value)
       File "/usr/src/build/rst.linker-1.10/.eggs/setuptools_scm-3.2.0-py3.5.egg/setuptools_scm/__init__.py", line 144, in get_version
         parsed_version = _do_parse(config)
       File "/usr/src/build/rst.linker-1.10/.eggs/setuptools_scm-3.2.0-py3.5.egg/setuptools_scm/__init__.py", line 111, in _do_parse
         "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
     LookupError: setuptools-scm was unable to detect version for '/usr/src/build/rst.linker-1.10'.

If the rst.linker v1.10 source code is downloaded from the PyPi site, then it builds without error.

The only difference between the files in v1.10 source code from this repository and the PyPi site is the setup.cfg file.

The setup.cfg file in this repository is missing an egg-info section

     --- rst.linker-1.10-Github/setup.cfg   2018-05-22 17:46:27.000000000 +0200
     +++ rst.linker-1.10-PyPi/setup.cfg     2018-05-22 17:50:54.000000000 +0200
     @@ -7,3 +7,8 @@

      [metadata]
      license_file = LICENSE
     +
     +[egg_info]
     +tag_build =
     +tag_date = 0
     +
~

**Comment by jaraco** [comment]
That's right, and that's by design. rst.linker relies on setuptools_scm to derive the package version from SCM tags. When you pull a raw zip file from GitHub, that metadata isn't present. You must either build from an SCM checkout or from the sdist as found on PyPI.
